a=10
b=9
c=8
d=7
e=6
f=5
g=4
h=3
i=2
j=1
k=0

print(str(k)+("*")+str(a)+"="+str(a * k))
print(str(j)+("*")+str(a)+"="+str(a * j))
print(str(i)+("*")+str(a)+"="+str(a * i))
print(str(h)+("*")+str(a)+"="+str(a * h))
print(str(g)+("*")+str(a)+"="+str(a * g))
print(str(f)+("*")+str(a)+"="+str(a * f))
print(str(e)+("*")+str(a)+"="+str(a * e))
print(str(d)+("*")+str(a)+"="+str(a * d))
print(str(c)+("*")+str(a)+"="+str(a * c))
print(str(b)+("*")+str(a)+"="+str(a * b))
print(str(a)+("*")+str(a)+"="+str(a * a))
